import { useState, useRef, useMemo } from "react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { useLocation } from "wouter";
import { Shield, Plus, Trash2, ArrowLeft, Image as ImageIcon, Upload, X, Pencil, Wand2, Search, Filter, ChevronLeft, ChevronRight } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { toast } from "sonner";
import { Link } from "wouter";

export default function AdminProducts() {
  const [, setLocation] = useLocation();
  const { user, loading } = useAuth({ redirectOnUnauthenticated: true, redirectPath: "/admin/login" });
  
  const [view, setView] = useState("list"); // "list" or "form"
  const [isUploading, setIsUploading] = useState(false);
  const [editingProduct, setEditingProduct] = useState(null); // null = create mode, product obj = edit mode

  const [title, setTitle] = useState("");
  const [handle, setHandle] = useState("");
  const [price, setPrice] = useState("");
  const [isOnSale, setIsOnSale] = useState(false);
  const [compareAtPrice, setCompareAtPrice] = useState("");
  const [isTrending, setIsTrending] = useState(false);
  const [description, setDescription] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [imageFile, setImageFile] = useState(null);
  const [imagePreview, setImagePreview] = useState("");
  const [tags, setTags] = useState("");

  const fileInputRef = useRef(null);
  const utils = trpc.useUtils();
  const { data: products = [], isLoading: isLoadingProducts } = trpc.commerce.products.list.useQuery();
  const { data: categories = [], isLoading: isLoadingCategories } = trpc.commerce.categories.list.useQuery();

  const [searchTerm, setSearchTerm] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("all");
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 10;

  const filteredProducts = useMemo(() => {
    return products.filter((prod) => {
      const matchesSearch = prod.title.toLowerCase().includes(searchTerm.toLowerCase()) || 
                            prod.handle.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesCategory = categoryFilter === "all" || prod.productType === categoryFilter;
      return matchesSearch && matchesCategory;
    });
  }, [products, searchTerm, categoryFilter]);

  const totalPages = Math.ceil(filteredProducts.length / itemsPerPage);
  const paginatedProducts = filteredProducts.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);

  // Reset to page 1 when filters change
  useMemo(() => {
    setCurrentPage(1);
  }, [searchTerm, categoryFilter]);

  const createMutation = trpc.admin.createProduct.useMutation({
    onSuccess: () => {
      toast.success("Product created successfully!");
      resetForm();
      setView("list");
      utils.commerce.products.list.invalidate();
    },
    onError: (err) => toast.error(err.message),
  });

  const updateMutation = trpc.admin.updateProduct.useMutation({
    onSuccess: () => {
      toast.success("Product updated successfully!");
      resetForm();
      setView("list");
      utils.commerce.products.list.invalidate();
    },
    onError: (err) => toast.error(err.message),
  });

  const deleteMutation = trpc.admin.deleteProduct.useMutation({
    onSuccess: () => {
      toast.success("Product deleted");
      utils.commerce.products.list.invalidate();
    },
    onError: (err) => toast.error(err.message),
  });

  const autoGenDescMutation = trpc.admin.autoGenerateDescription.useMutation({
    onSuccess: (data) => {
      setDescription(data.description);
      toast.success("Description generated!");
    },
    onError: (err) => toast.error(err.message),
  });

  const resetForm = () => {
    setTitle("");
    setHandle("");
    setPrice("");
    setIsOnSale(false);
    setCompareAtPrice("");
    setIsTrending(false);
    setDescription("");
    setCategoryId("");
    setImageFile(null);
    setImagePreview("");
    setTags("");
    setEditingProduct(null);
  };

  const openEditForm = (prod) => {
    setEditingProduct(prod);
    setTitle(prod.title || "");
    setHandle(prod.handle || "");
    setPrice(prod.priceRange?.min?.amount?.toString() || "");
    setIsOnSale((prod.compareAtPrice && prod.compareAtPrice > prod.priceRange?.min?.amount) ? true : false);
    setCompareAtPrice(prod.compareAtPrice ? prod.compareAtPrice.toString() : "");
    setIsTrending(prod.isTrending || false);
    setDescription(prod.description || "");
    // Find matching category by productType (name)
    const matchedCat = categories.find(c => c.name.toLowerCase() === (prod.productType || "").toLowerCase());
    setCategoryId(matchedCat?.id || "");
    setImageFile(null);
    setImagePreview(prod.images?.[0]?.url || "");
    setTags((prod.tags || []).join(", "));
    setView("form");
  };

  if (loading || isLoadingProducts || isLoadingCategories) return null;
  if (!user || user.role !== "admin") {
    setLocation("/");
    return null;
  }

  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      if (file.size > 5 * 1024 * 1024) {
        toast.error("Image must be less than 5MB");
        return;
      }
      setImageFile(file);
      const url = URL.createObjectURL(file);
      setImagePreview(url);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!categoryId) {
      toast.error("Please select a category");
      return;
    }

    if (isOnSale && parseFloat(compareAtPrice) <= parseFloat(price)) {
      toast.error("The Original Price must be HIGHER than the Current Selling Price to put an item on sale!");
      return;
    }

    setIsUploading(true);
    let uploadedImageUrl = undefined;

    if (imageFile) {
      const formData = new FormData();
      formData.append("image", imageFile);
      try {
        const res = await fetch("/api/upload", {
          method: "POST",
          body: formData,
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data.error || "Failed to upload image");
        uploadedImageUrl = data.url;
      } catch (err) {
        toast.error(err.message);
        setIsUploading(false);
        return;
      }
    }

    if (editingProduct) {
      // Edit mode — use existing image if no new one uploaded
      const existingImageUrl = editingProduct.images?.[0]?.url;
      updateMutation.mutate({
        productId: editingProduct.id,
        title,
        price: parseFloat(price),
        compareAtPrice: isOnSale && compareAtPrice ? parseFloat(compareAtPrice) : null,
        isTrending,
        description,
        categoryId,
        imageUrl: uploadedImageUrl || existingImageUrl || "",
        tags: tags ? tags.split(",").map(t => t.trim()) : []
      }, {
        onSettled: () => setIsUploading(false)
      });
    } else {
      // Create mode
      createMutation.mutate({
        title,
        handle,
        price: parseFloat(price),
        compareAtPrice: isOnSale && compareAtPrice ? parseFloat(compareAtPrice) : null,
        isTrending,
        description,
        categoryId,
        imageUrl: uploadedImageUrl,
        tags: tags ? tags.split(",").map(t => t.trim()) : undefined
      }, {
        onSettled: () => setIsUploading(false)
      });
    }
  };

  const isPending = createMutation.isPending || updateMutation.isPending || isUploading;

  return (
    <div className="min-h-screen bg-muted/20">
      <motion.div
        className="bg-background border-b border-border py-8 px-4"
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className="w-16 h-16 bg-primary text-primary-foreground flex items-center justify-center shadow-lg">
              <Shield className="w-8 h-8" />
            </div>
            <div>
              <h1 className="text-3xl md:text-4xl font-black uppercase tracking-tighter text-foreground mb-1">Manage Products</h1>
              <Link href="/admin">
                <span className="text-primary font-bold uppercase tracking-widest text-xs flex items-center gap-1 cursor-pointer hover:underline">
                  <ArrowLeft className="w-3 h-3" /> Back to Dashboard
                </span>
              </Link>
            </div>
          </div>
          {view === "list" ? (
            <button 
              onClick={() => { resetForm(); setView("form"); }}
              className="bg-foreground text-background font-black uppercase tracking-widest px-6 py-3 flex items-center gap-2 hover:bg-primary transition-colors text-sm"
            >
              <Plus className="w-5 h-5" /> Add Product
            </button>
          ) : (
            <button 
              onClick={() => { setView("list"); resetForm(); }}
              className="border-2 border-foreground text-foreground font-black uppercase tracking-widest px-6 py-3 flex items-center gap-2 hover:bg-muted transition-colors text-sm"
            >
              Cancel
            </button>
          )}
        </div>
      </motion.div>

      <div className="max-w-7xl mx-auto px-4 py-12">
        <AnimatePresence mode="wait">
          {view === "list" ? (
            <motion.div 
              key="list"
              initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }}
            >
              <div className="flex flex-col sm:flex-row gap-4 mb-6">
                <div className="relative flex-1">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                  <input
                    type="text"
                    placeholder="Search products..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="w-full pl-10 pr-4 py-3 bg-background border border-border text-sm focus:outline-none focus:border-primary transition-colors"
                  />
                </div>
                <div className="relative w-full sm:w-64">
                  <Filter className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                  <select
                    value={categoryFilter}
                    onChange={(e) => setCategoryFilter(e.target.value)}
                    className="w-full pl-10 pr-4 py-3 bg-background border border-border text-sm focus:outline-none focus:border-primary transition-colors cursor-pointer appearance-none"
                  >
                    <option value="all">All Categories</option>
                    {categories.map(cat => (
                      <option key={cat.id} value={cat.name}>{cat.name}</option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="bg-background border border-border overflow-hidden">
                <div className="grid-cols-12 gap-4 p-4 border-b border-border text-xs font-black uppercase tracking-widest text-muted-foreground bg-muted/20 hidden md:grid">
                  <div className="col-span-1">Img</div>
                  <div className="col-span-4">Product Info</div>
                  <div className="col-span-3">Category</div>
                  <div className="col-span-2">Price</div>
                  <div className="col-span-2 text-right">Actions</div>
                </div>
                {paginatedProducts.length === 0 ? (
                  <div className="p-16 text-center text-muted-foreground font-bold uppercase tracking-widest">No products found.</div>
                ) : (
                  paginatedProducts.map(prod => (
                  <div key={prod.id} className="grid grid-cols-1 md:grid-cols-12 gap-4 p-4 border-b border-border items-center hover:bg-muted/10 transition-colors">
                    <div className="md:col-span-1 hidden md:block">
                      <div className="w-12 h-12 bg-muted border border-border overflow-hidden flex items-center justify-center">
                        {prod.images && prod.images[0] ? (
                          <img src={prod.images[0].url} alt={prod.title} className="w-full h-full object-cover" />
                        ) : <ImageIcon className="w-5 h-5 text-muted-foreground" />}
                      </div>
                    </div>
                    <div className="md:col-span-4 flex flex-col">
                      <div className="flex items-center gap-2">
                        <span className="font-black uppercase tracking-tighter text-foreground text-lg line-clamp-1">{prod.title}</span>
                        {prod.compareAtPrice > prod.priceRange?.min?.amount && (
                          <span className="bg-primary text-primary-foreground text-[8px] px-2 py-0.5 font-black uppercase tracking-widest">Sale</span>
                        )}
                        {prod.isTrending && (
                          <span className="bg-foreground text-background text-[8px] px-2 py-0.5 font-black uppercase tracking-widest">Trending</span>
                        )}
                      </div>
                      <span className="text-xs text-muted-foreground font-bold">{prod.handle}</span>
                    </div>
                    <div className="md:col-span-3 text-sm font-bold uppercase tracking-wider text-muted-foreground">
                      {prod.productType || "—"}
                    </div>
                    <div className="md:col-span-2 text-foreground font-black text-lg">
                      ₹{prod.priceRange.min.amount}
                      {prod.compareAtPrice > prod.priceRange.min.amount && (
                        <span className="text-xs text-muted-foreground line-through ml-2">₹{prod.compareAtPrice}</span>
                      )}
                    </div>
                    <div className="md:col-span-2 flex justify-end gap-2">
                      <button 
                        onClick={() => openEditForm(prod)}
                        className="p-3 text-muted-foreground hover:text-primary hover:bg-primary/10 transition-colors border border-transparent hover:border-primary/20"
                        title="Edit Product"
                      >
                        <Pencil className="w-4 h-4" />
                      </button>
                      <button 
                        onClick={() => {
                          if (confirm("Delete this product?")) deleteMutation.mutate({ productId: prod.id });
                        }}
                        className="p-3 text-muted-foreground hover:text-destructive hover:bg-destructive/10 transition-colors border border-transparent hover:border-destructive/20"
                        title="Delete Product"
                      >
                        <Trash2 className="w-5 h-5" />
                      </button>
                    </div>
                  </div>
                ))
              )}
              </div>

              {totalPages > 1 && (
                <div className="flex justify-center items-center gap-4 mt-8">
                  <button
                    onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                    disabled={currentPage === 1}
                    className="p-2 bg-background border border-border hover:bg-muted disabled:opacity-50 transition-colors"
                  >
                    <ChevronLeft className="w-5 h-5" />
                  </button>
                  <span className="text-sm font-bold uppercase tracking-widest">
                    Page {currentPage} of {totalPages}
                  </span>
                  <button
                    onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                    disabled={currentPage === totalPages}
                    className="p-2 bg-background border border-border hover:bg-muted disabled:opacity-50 transition-colors"
                  >
                    <ChevronRight className="w-5 h-5" />
                  </button>
                </div>
              )}
            </motion.div>
          ) : (
            <motion.div 
              key="form"
              initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 20 }}
              className="max-w-4xl mx-auto bg-background border border-border p-8"
            >
              <h2 className="text-3xl font-black uppercase tracking-tighter text-foreground mb-2 pb-4 border-b border-border flex items-center gap-3">
                {editingProduct ? (
                  <><Pencil className="w-7 h-7 text-primary" /> Edit Product</>
                ) : (
                  <><Plus className="w-7 h-7 text-primary" /> Create New Product</>
                )}
              </h2>
              {editingProduct && (
                <p className="text-xs text-muted-foreground font-bold uppercase tracking-widest mb-6">
                  Editing: <span className="text-primary">{editingProduct.title}</span>
                </p>
              )}
              <form onSubmit={handleSubmit} className="space-y-8 mt-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  {/* Left Column: Details */}
                  <div className="space-y-6">
                    <div>
                      <label className="text-xs font-black uppercase tracking-widest text-foreground block mb-2">Title</label>
                      <input 
                        type="text" value={title} 
                        onChange={(e) => {
                          setTitle(e.target.value);
                          if (!editingProduct && (!handle || handle === title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, ''))) {
                            setHandle(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, ''));
                          }
                        }}
                        required
                        className="w-full bg-muted/30 border border-border px-4 py-4 text-sm focus:outline-none focus:border-primary transition-colors" 
                      />
                    </div>
                    
                    {!editingProduct && (
                      <div>
                        <label className="text-xs font-black uppercase tracking-widest text-foreground block mb-2">Handle (URL Slug)</label>
                        <input 
                          type="text" value={handle} onChange={(e) => setHandle(e.target.value)} required
                          className="w-full bg-muted/30 border border-border px-4 py-4 text-sm focus:outline-none focus:border-primary transition-colors lowercase" 
                        />
                      </div>
                    )}

                    <div>
                      <label className="text-xs font-black uppercase tracking-widest text-foreground block mb-2">Current Selling Price (₹)</label>
                      <input 
                        type="number" min="0" step="0.01" value={price} onChange={(e) => setPrice(e.target.value)} required
                        className="w-full bg-muted/30 border border-border px-4 py-4 focus:outline-none focus:border-primary transition-colors font-black text-lg" 
                      />
                    </div>

                    <div className="flex items-center gap-4 border border-border p-4 bg-muted/10">
                      <div className="flex items-center gap-2">
                        <input 
                          type="checkbox" 
                          id="onSale" 
                          checked={isOnSale} 
                          onChange={(e) => setIsOnSale(e.target.checked)} 
                          className="w-4 h-4 text-primary focus:ring-primary border-border bg-muted/30 cursor-pointer"
                        />
                        <label htmlFor="onSale" className="text-xs font-black uppercase tracking-widest text-foreground cursor-pointer">
                          Product is on Sale
                        </label>
                      </div>
                    </div>

                    {isOnSale && (
                      <div>
                        <label className="text-xs font-black uppercase tracking-widest text-foreground block mb-2">Original Higher Price (Compare At) (₹)</label>
                        <input 
                          type="number" min="0" step="0.01" value={compareAtPrice} onChange={(e) => setCompareAtPrice(e.target.value)}
                          className="w-full bg-muted/30 border border-border px-4 py-4 focus:outline-none focus:border-primary transition-colors font-black text-lg text-muted-foreground" 
                          placeholder="Must be higher than selling price" required={isOnSale}
                        />
                      </div>
                    )}

                    <div className="flex items-center gap-2">
                      <input 
                        type="checkbox" 
                        id="trending" 
                        checked={isTrending} 
                        onChange={(e) => setIsTrending(e.target.checked)} 
                        className="w-4 h-4 text-primary focus:ring-primary border-border bg-muted/30"
                      />
                      <label htmlFor="trending" className="text-xs font-black uppercase tracking-widest text-foreground cursor-pointer">
                        Mark as Trending Right Now
                      </label>
                    </div>

                    <div>
                      <label className="text-xs font-black uppercase tracking-widest text-foreground block mb-2">Category</label>
                      <select 
                        value={categoryId} onChange={(e) => setCategoryId(e.target.value)} required
                        className="w-full bg-muted/30 border border-border px-4 py-4 text-sm focus:outline-none focus:border-primary transition-colors cursor-pointer"
                      >
                        <option value="" disabled>Select a Category...</option>
                        {categories.map(cat => (
                          <option key={cat.id} value={cat.id}>{cat.name}</option>
                        ))}
                      </select>
                    </div>

                    <div>
                      <label className="text-xs font-black uppercase tracking-widest text-foreground block mb-2">Tags (Comma separated)</label>
                      <input 
                        type="text" value={tags} onChange={(e) => setTags(e.target.value)}
                        className="w-full bg-muted/30 border border-border px-4 py-4 text-sm focus:outline-none focus:border-primary transition-colors" 
                        placeholder="e.g. Sale, New, Summer"
                      />
                    </div>
                  </div>

                  {/* Right Column: Image & Desc */}
                  <div className="space-y-6">
                    <div>
                      <label className="text-xs font-black uppercase tracking-widest text-foreground block mb-2">
                        Product Image {editingProduct && imagePreview && !imageFile && <span className="text-muted-foreground normal-case font-normal">(current image shown)</span>}
                      </label>
                      <div 
                        onClick={() => fileInputRef.current?.click()}
                        className={`w-full h-48 border-2 border-dashed ${imagePreview ? "border-primary" : "border-border hover:border-primary"} bg-muted/20 flex flex-col items-center justify-center cursor-pointer transition-colors relative overflow-hidden group`}
                      >
                        {imagePreview ? (
                          <>
                            <img src={imagePreview} alt="Preview" className="w-full h-full object-cover" />
                            <div className="absolute inset-0 bg-background/80 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                              <span className="font-bold uppercase tracking-widest text-sm flex items-center gap-2"><Upload className="w-4 h-4"/> Change Image</span>
                            </div>
                          </>
                        ) : (
                          <div className="text-center p-6">
                            <Upload className="w-10 h-10 text-muted-foreground mx-auto mb-4" />
                            <p className="text-foreground font-bold uppercase tracking-widest text-sm mb-1">Upload Image</p>
                            <p className="text-muted-foreground text-xs">JPG, PNG, WebP up to 5MB</p>
                          </div>
                        )}
                        <input 
                          type="file" 
                          ref={fileInputRef} 
                          onChange={handleImageChange}
                          accept="image/*"
                          className="hidden"
                        />
                      </div>
                      {imagePreview && (
                        <button 
                          type="button" 
                          onClick={(e) => { e.stopPropagation(); setImageFile(null); setImagePreview(""); }}
                          className="mt-2 text-xs font-bold uppercase tracking-widest text-destructive hover:underline flex items-center gap-1"
                        >
                          <X className="w-3 h-3"/> Remove Image
                        </button>
                      )}
                    </div>

                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <label className="text-xs font-black uppercase tracking-widest text-foreground">Description</label>
                        <button 
                          type="button" 
                          onClick={() => {
                            const catName = categories.find(c => c.id === categoryId)?.name;
                            autoGenDescMutation.mutate({ title: title || "New Product", category: catName });
                          }}
                          disabled={autoGenDescMutation.isPending}
                          className="text-[10px] font-black uppercase tracking-widest bg-secondary text-secondary-foreground px-3 py-1 flex items-center gap-1 hover:opacity-80 disabled:opacity-50"
                        >
                          <Wand2 className="w-3 h-3" /> {autoGenDescMutation.isPending ? "Generating..." : "Auto-Generate"}
                        </button>
                      </div>
                      <textarea 
                        value={description} onChange={(e) => setDescription(e.target.value)} 
                        className="w-full h-[150px] bg-muted/30 border border-border px-4 py-4 text-sm focus:outline-none focus:border-primary transition-colors resize-y" 
                        placeholder="Write a detailed product description..."
                      />
                    </div>
                  </div>
                </div>

                <div className="pt-8 border-t border-border flex justify-end">
                  <button 
                    type="submit" disabled={isPending}
                    className="bg-foreground text-background font-black uppercase tracking-widest px-12 py-5 flex items-center justify-center gap-3 hover:bg-primary transition-colors disabled:opacity-50 text-lg"
                  >
                    {isPending ? (
                      <motion.div className="w-6 h-6 border-2 border-background border-t-transparent rounded-full" animate={{ rotate: 360 }} transition={{ duration: 0.8, repeat: Infinity, ease: "linear" }} />
                    ) : editingProduct ? "Save Changes" : "Publish Product"}
                  </button>
                </div>
              </form>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
